services:
  - type: web
    name: tienda-virtual
    env: php
    plan: free
    region: oregon
    buildCommand: 
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql