services:
  - type: web
    name: tienda-virtual
    env: docker
    region: oregon
    plan: free
    rootDir: .
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mysql
